### ISSUE TITLE
TESTING！

### ISSUE THREAD

**Issue by monster-xie** [KAdamek/GPU_Overlap-and-save_convolution#2]
After enabling the TESTING switch, the overlap-save algorithm of the custom FFT using shared memory produces results consistent with those obtained using the cuFFT library; otherwise, there are discrepancies. I would like to ask whether not enabling the TESTING switch affects the accuracy of the filtering results.

**Comment by reichold** [comment]
Dear Karel
(cc Scott)
I hope this message finds you and your loved ones in good spirit and health.
It is nice to hear from you with news about this code.
Let us have a look at our results with and without testing enabled and report back to you.
cheers
Armin

From: monster-xie ***@***.***>
Sent: 27 September 2024 07:39
To: KAdamek/GPU_Overlap-and-save_convolution ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KAdamek/GPU_Overlap-and-save_convolution] TESTING！ (Issue #2)


After enabling the TESTING switch, the overlap-save algorithm of the custom FFT using shared memory produces results consistent with those obtained using the cuFFT library; otherwise, there are discrepancies. I would like to ask whether not enabling the TESTING switch affects the accuracy of the filtering results.

**Comment by reichold** [comment]
Dear Karel
Scott just told me that the part of your code we use is not using the testing function at all.
So we cannot comment on the consequences.
Sorry
Armin

From: Armin Reichold
Sent: 27 September 2024 08:41
To: KAdamek/GPU_Overlap-and-save_convolution ***@***.***>
Cc: Scott DeGraw ***@***.***>
Subject: RE: [KAdamek/GPU_Overlap-and-save_convolution] TESTING！ (Issue #2)

Dear Karel
(cc Scott)
I hope this message finds you and your loved ones in good spirit and health.
It is nice to hear from you with news about this code.
Let us have a look at our results with and without testing enabled and report back to you.
cheers
Armin

From: monster-xie ***@***.***>
Sent: 27 September 2024 07:39
To: KAdamek/GPU_Overlap-and-save_convolution ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KAdamek/GPU_Overlap-and-save_convolution] TESTING！ (Issue #2)


After enabling the TESTING switch, the overlap-save algorithm of the custom FFT using shared memory produces results consistent with those obtained using the cuFFT library; otherwise, there are discrepancies. I would like to ask whether not enabling the TESTING switch affects the accuracy of the filtering results.

**Comment by monster-xie** [comment]
Thank you very much, I have already identified the problem. It seems to be an issue with performing the FFT on the filter coefficients.

**Comment by monster-xie** [comment]
thanks！
